name: Windows CI with Ngrok

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile ngrok.zip

    - name: Extract Ngrok
      run: Expand-Archive -Path ngrok.zip -DestinationPath .

    - name: Check Ngrok Version
      run: ./ngrok version

    - name: Replace Ngrok Executable
      run: |
        # Remove old ngrok executable
        Remove-Item ngrok.exe
        # Download the latest ngrok executable
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile ngrok.zip
        # Extract the ngrok executable
        Expand-Archive -Path ngrok.zip -DestinationPath .
        # Verify ngrok version after update
        ./ngrok version

    - name: Authentication
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        # Enable Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        # Allow connections only from computers running Remote Desktop with Network Level Authentication
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
    - name: Set Local User Password
      run: net user runneradmin MySecurePassword123!

    - name: Create Tunnel
      run: ./ngrok tcp 3389
      
