name: Windows CI with Ngrok

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install Ngrok
      run: choco install ngrok -y

    - name: Update Ngrok
      run: |
        ngrok update

    - name: Authentication
      run: |
        ngrok authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Local User Password
      run: net user runneradmin MySecurePassword123!

    - name: Create Tunnel
      run: |
        ngrok tcp 3389
